name: Test Continuous Integration - Architecture Scripts

on:
  push:
    branches:
      - main

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Grant execution permissions to scripts
        run: |
          chmod +x ./Architecture/MainInfrastructure/environment.sh
          chmod +x ./Architecture/DatalakeServer/datalake_server.sh
          chmod +x ./Architecture/DatamartServer/datamart_server.sh
          chmod +x ./Architecture/Crawler/crawler.sh
          chmod +x ./Architecture/DatalakeServer/BuildDatalake/build_datalake_server.sh
          chmod +x ./Architecture/APIServers/PathServer/path_server.sh
          chmod +x ./Architecture/DatamartServer/BuildDatamart/build_datamart_server.sh
          chmod +x ./Architecture/APIServers/NodeConServer/node_server.sh
          chmod +x ./Architecture/APIServers/LambdasServer/BuildLambdas/build_lambdas.sh
          chmod +x ./Architecture/APIServers/LambdasServer/lambdas_server.sh
          chmod +x ./Architecture/APIServers/NginxServer/nginx_server.sh
          chmod +x ./Architecture/init.sh

      - name: Execute script
        run: ./Architecture/init.sh

      - name: Output results
        run: echo "Deployment completed successfully."
