name: CI for AllPaths Module

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    # 1. Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # 3. Instalar dependencias
    - name: Install dependencies
      run: |
        cd API/AllPaths
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage

    # 4. Exportar variables de entorno
    - name: Set environment variables
      run: |
        echo "NEO4J_URI=bolt://localhost:7687" >> $GITHUB_ENV
        echo "NEO4J_USER=neo4j" >> $GITHUB_ENV
        echo "NEO4J_PASSWORD=password" >> $GITHUB_ENV

    # 5. Ejecutar los tests con cobertura desde el directorio de API
    - name: Run AllPaths tests with coverage
      run: |
        cd API
        coverage run -m unittest tests/test_allpaths.py
        coverage report
