name: DatalakeBuilder CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r DatalakeBuilder/requirements.txt
        pip install coverage

    - name: Download NLTK data
      run: |
        python -m nltk.downloader all

    - name: Run tests with coverage
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        coverage run -m unittest discover -s DatalakeBuilder/tests
        coverage report
