name: CI for MaxDistance Module

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      neo4j:
        image: neo4j:5.5
        ports:
          - 7687:7687
        options: >-
          --env=NEO4J_AUTH=none

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        pip install -r API/MaxDistance/webpage/requirements.txt
        pip show neo4j  # Verifica que neo4j se haya instalado correctamente

    - name: Set environment variables
      run: |
        echo "NEO4J_URI=bolt://localhost:7687" >> $GITHUB_ENV
        echo "NEO4J_USER=neo4j" >> $GITHUB_ENV
        echo "NEO4J_PASSWORD=password" >> $GITHUB_ENV

    - name: Run MaxDistance tests with coverage
      run: |
        cd API
        coverage run -m unittest tests/test_maxdistance.py
        coverage report
