name: CI for ShortestPath Module

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r API/ShortestPath/requirements.txt

      # 4. Exportar variables de entorno
      - name: Set environment variables
        run: |
          echo "NEO4J_URI=bolt://localhost:7687" >> $GITHUB_ENV
          echo "NEO4J_USER=neo4j" >> $GITHUB_ENV
          echo "NEO4J_PASSWORD=password" >> $GITHUB_ENV

      # 5. Ejecutar los tests desde el directorio de API
      - name: Run ShortestPath tests
        run: |
          cd API
          python -m unittest tests/test_shortestpath.py
